version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: shopflow-broker
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=gaptech
      - RABBITMQ_DEFAULT_PASS=gaptech_suporte
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  pedido:
    build: ./servicos/pedido
    container_name: shopflow-pedido
    ports:
      - "8001:8001"
    env_file:
      - .env  # Garante a leitura dinâmica das credenciais da HostGator
    environment:
      - PORT=8001
      - BROKER_HOST=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy

  pagamento:
    build: ./servicos/pagamento
    container_name: shopflow-pagamento
    ports:
      - "8002:8002"
    env_file:
      - .env  # Garante a leitura dinâmica das credenciais da HostGator
    environment:
      - PORT=8002
      - BROKER_HOST=rabbitmq
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      rabbitmq:
        condition: service_healthy

  logistica:
    build: ./servicos/logistica
    container_name: shopflow-logistica
    ports:
      - "8003:8003"
    env_file:
      - .env  # Garante a leitura dinâmica das credenciais da HostGator
    environment:
      - PORT=8003
      - BROKER_HOST=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy

  mock_antifraude:
    build: ./servicos/pedido
    container_name: mock-antifraude
    command: python /app_mock/mock_antifraude.py
    volumes:
      - ./mocks:/app_mock
    env_file:
      - .env
    environment:
      - BROKER_HOST=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy

  mock_catalogo:
    build: ./servicos/pedido
    container_name: mock-catalogo
    command: python /app_mock/mock_catalogo.py
    volumes:
      - ./mocks:/app_mock
    env_file:
      - .env
    environment:
      - BROKER_HOST=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy

  dashboard:
    image: python:3.11-slim
    container_name: shopflow-dashboard
    ports:
      - "8050:8050"
    # CORREÇÃO: Instala as dependências e roda o seu arquivo real sem apagá-lo
    command: sh -c "pip install streamlit requests pandas pymysql && streamlit run app.py --server.port 8050 --server.address 0.0.0.0"
    working_dir: /app
    volumes:
      - ./dashboard/app:/app  # Mapeia a sua pasta local de desenvolvimento do Dashboard
    env_file:
      - .env
    depends_on:
      - pedido